# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
# CI and CD test with staging, production with approval

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm install
    displayName: "npm install"

  - task: Docker@2
    displayName: Container registry login
    inputs:
      command: login
      containerRegistry: LTRCode3DockerRegistryConnection

  - task: Docker@2
    displayName: Build and Push
    inputs:
      command: buildAndPush
      repository: auth_server_ts
      tags: |
        $(Build.BuildId)
